server:
  port: 9008

spring:
  application:
    name: service-config
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.132:8848
        username: nacos
        password: nacos
        namespace: public
