server:
  port: 9005

spring:
  application:
    name: service-order-ribbon
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.132:8848
        username: nacos
        password: nacos
        namespace: public



